<?php

namespace Database\Seeders;

use App\Models\AssetType;
use Illuminate\Database\Seeder;

class AssetTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $timestamp = now();

        $assetTypes = [
            [
                'name' => 'Low Height Cabinet',
                'code' => 'LHC',
                'default_image' => null,
                'height' => 3.00,
                'width' => 4.00,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 2,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Accessories Gondola',
                'code' => 'ACG',
                'default_image' => null,
                'height' => 6.00,
                'width' => 3.00,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 4,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 2,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Nailpolish Gondola',
                'code' => 'NPG',
                'default_image' => null,
                'height' => 6.00,
                'width' => 3.00,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 4,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 2,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Cash Counter',
                'code' => 'CAC',
                'default_image' => null,
                'height' => 3.00,
                'width' => 4.00,
                'depth' => 2.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 2,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 0,
                'has_asset_self' => 1,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Skin Analyzer Table',
                'code' => 'SAT',
                'default_image' => null,
                'height' => 3.00,
                'width' => 2.50,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 1,
                'has_kv_space' => 0,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 0,
                'has_asset_self' => 0,
                'total_kv_slot' => 0,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'FSU Type - 1',
                'code' => 'FS1',
                'default_image' => null,
                'height' => 5.00,
                'width' => 2.50,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 3,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'FSU Type - 2',
                'code' => 'FS2',
                'default_image' => null,
                'height' => 5.50,
                'width' => 2.50,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 4,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'FSU Type - 3',
                'code' => 'FS3',
                'default_image' => null,
                'height' => 6.00,
                'width' => 2.50,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 4,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 2,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Center Gondola-3',
                'code' => 'CG3',
                'default_image' => null,
                'height' => 6.00,
                'width' => 3.00,
                'depth' => 2.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 4,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 2,
                'is_double_side' => 1,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Home Care Gondola',
                'code' => 'HCG',
                'default_image' => null,
                'height' => 6.00,
                'width' => 4.00,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 4,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 2,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => '2 Feet Wall Gondola',
                'code' => 'WG2',
                'default_image' => null,
                'height' => 7.00,
                'width' => 2.00,
                'depth' => 1.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 5,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 0,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => '4 Feet Wall Gondola',
                'code' => 'WG4',
                'default_image' => null,
                'height' => 7.00,
                'width' => 4.00,
                'depth' => 1.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 5,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 0,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => '2 Feet Bothside Open Gondola',
                'code' => 'BO2',
                'default_image' => null,
                'height' => 6.00,
                'width' => 2.00,
                'depth' => 2.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 4,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 2,
                'is_double_side' => 1,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => '4 Feet Bothside Open Gondola',
                'code' => 'BO4',
                'default_image' => null,
                'height' => 6.00,
                'width' => 4.00,
                'depth' => 2.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 4,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 2,
                'is_double_side' => 1,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => '2 Feet Bothside Open Low Height Gondola',
                'code' => 'BL2',
                'default_image' => null,
                'height' => 4.00,
                'width' => 2.00,
                'depth' => 2.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 3,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 1,
                'is_double_side' => 1,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => '4 Feet Bothside Open Low Height Gondola',
                'code' => 'BL4',
                'default_image' => null,
                'height' => 4.00,
                'width' => 4.00,
                'depth' => 2.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 3,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 1,
                'is_double_side' => 1,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Center Gondola-2 (SSCG)',
                'code' => 'CG2',
                'default_image' => null,
                'height' => 6.00,
                'width' => 2.00,
                'depth' => 2.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 4,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 2,
                'is_double_side' => 1,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Front Display Gondola',
                'code' => 'FDG',
                'default_image' => null,
                'height' => 6.00,
                'width' => 3.00,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 4,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 2,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Makeup Mirror Module',
                'code' => 'MMM',
                'default_image' => null,
                'height' => 6.00,
                'width' => 3.00,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 3,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 1,
                'need_asset_planogram' => 0,
                'has_asset_self' => 0,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Gift Box Gondola',
                'code' => 'GBG',
                'default_image' => null,
                'height' => 5.00,
                'width' => 3.00,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 3,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Gift Wrapping Stand',
                'code' => 'GWS',
                'default_image' => null,
                'height' => 4.00,
                'width' => 3.00,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 2,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 0,
                'has_asset_self' => 1,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Gondola',
                'code' => 'GON',
                'default_image' => null,
                'height' => 6.00,
                'width' => 4.00,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 4,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 2,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Wall Display Rack',
                'code' => 'WDR',
                'default_image' => null,
                'height' => 7.00,
                'width' => 3.00,
                'depth' => 1.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 5,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 0,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'End Cap Display',
                'code' => 'ECD',
                'default_image' => null,
                'height' => 6.00,
                'width' => 2.50,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 3,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Counter Display Unit',
                'code' => 'CDU',
                'default_image' => null,
                'height' => 2.50,
                'width' => 2.00,
                'depth' => 1.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => 2,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 1,
                'has_asset_self' => 1,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Billboard',
                'code' => 'BBD',
                'default_image' => null,
                'height' => 4.00,
                'width' => 8.00,
                'depth' => 0.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => null,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 1,
                'need_asset_planogram' => 0,
                'has_asset_self' => 0,
                'total_kv_slot' => 1,
                'is_double_side' => 1,
                'is_ground_type_assets' => 0,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Banner',
                'code' => 'BAN',
                'default_image' => null,
                'height' => 6.00,
                'width' => 2.50,
                'depth' => 0.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => null,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 1,
                'need_asset_planogram' => 0,
                'has_asset_self' => 0,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 0,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Standee',
                'code' => 'STD',
                'default_image' => null,
                'height' => 6.00,
                'width' => 2.00,
                'depth' => 1.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => null,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 1,
                'need_asset_planogram' => 0,
                'has_asset_self' => 0,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Light Box',
                'code' => 'LTB',
                'default_image' => null,
                'height' => 4.00,
                'width' => 3.00,
                'depth' => 0.50,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => null,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 1,
                'need_asset_planogram' => 0,
                'has_asset_self' => 0,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 0,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'LED TV',
                'code' => 'LED',
                'default_image' => null,
                'height' => 55.00,
                'width' => 0.00,
                'depth' => 0.00,
                'dimention_unit_name' => 'in',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 1,
                'total_self' => null,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 0,
                'has_asset_self' => 0,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 0,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'LCD TV',
                'code' => 'LCD',
                'default_image' => null,
                'height' => 43.00,
                'width' => 0.00,
                'depth' => 0.00,
                'dimention_unit_name' => 'in',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 1,
                'total_self' => null,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 0,
                'need_asset_planogram' => 0,
                'has_asset_self' => 0,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 0,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Window Display',
                'code' => 'WND',
                'default_image' => null,
                'height' => 6.00,
                'width' => 5.00,
                'depth' => 1.00,
                'dimention_unit_name' => 'ft',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => null,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 1,
                'need_asset_planogram' => 0,
                'has_asset_self' => 0,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 0,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'name' => 'Shelf Branding Strip',
                'code' => 'SHB',
                'default_image' => null,
                'height' => 3.00,
                'width' => 36.00,
                'depth' => 0.00,
                'dimention_unit_name' => 'in',
                'default_price' => 0,
                'status' => 1,
                'is_digital' => 0,
                'total_self' => null,
                'has_kv_space' => 1,
                'has_default_dimension' => 1,
                'need_asset_image' => 1,
                'need_asset_planogram' => 0,
                'has_asset_self' => 0,
                'total_kv_slot' => 1,
                'is_double_side' => 0,
                'is_ground_type_assets' => 0,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
        ];

        AssetType::upsert(
            $assetTypes,
            ['code'],
            [
                'name',
                'default_image',
                'height',
                'width',
                'depth',
                'dimention_unit_name',
                'default_price',
                'status',
                'is_digital',
                'total_self',
                'has_kv_space',
                'has_default_dimension',
                'need_asset_image',
                'need_asset_planogram',
                'has_asset_self',
                'total_kv_slot',
                'is_double_side',
                'is_ground_type_assets',
                'updated_at',
            ]
        );
    }
}
